version: '3'

services:
    web:
        image: python:3.6
        container_name: spintec-noticias
        volumes:
            - .:/home/application/current
        working_dir: /home/application/current
        ports:
            - "5000:5000"
        depends_on:
            - db
        command: tail -f /dev/null
    db:
        image: mongo
        container_name: spintec-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
