"""initial version

Revision ID: 907ce1b18bc5
Revises:
Create Date: 2021-10-10 14:26:23.993605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907ce1b18bc5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('autors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('noticias',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('autor_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['autors.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('noticias')
    op.drop_table('users')
    op.drop_table('autors')
    # ### end Alembic commands ###
